export const START_DOWNLOADING_ALBUM = "START_DOWNLOADING_ALBUM";
export const START_DOWNLOADING_IMAGE = "START_DOWNLOADING_IMAGE";
export const DONE_DOWNLOADING_IMAGE = "DONE_DOWNLOADING_IMAGE";
export const DONE_ALL_DOWNLOADS = "DONE_ALL_DOWNLOADS";

export const RETRY_FAILED_DOWNLOAD = "RETRY_FAILED_DOWNLOAD";

export const RESTART_APP = "RESTART_APP";
